export { default as AuthRouter } from '@routers/auth'
export { default as UserRouter } from '@routers/users'
export { default as ClientRouter } from '@routers/clients'
export { default as ProjectRouter } from '@routers/projects'
export { default as PaymentRouter } from '@routers/payments'
