export { default as AuthRouter } from '@src/routers/auth'
export { default as UserRouter } from '@src/routers/users'
export { default as ClientRouter } from '@src/routers/clients'
export { default as ProjectRouter } from '@src/routers/projects'
export { default as PaymentRouter } from '@src/routers/payments'
